Fix issue with direct import of transcriptic objects
Summary: Fixed issue with a change which broke backwards compatibility for importing jupyter objects directly. I.e. `from transcriptic import Run`

Test Plan:
Without required dependency (pandas)
```
>>> from transcriptic import Run
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Run'
```

With required dependencies (`pip install transcriptic[jupyter]`)
```
>>> from transcriptic import Run
>>>
```

Reviewers: eric, jim

Differential Revision: https://work.r23s.net/D8435